Update tests and compatibility
divio/django-simple-sso pull request #73
Opened 2024-03-25 07:34 UTC by FinalAngel

2024-03-25 10:31 UTC, fscherf requested changes

2024-03-25 10:31 UTC, fscherf commented on README.rst
> +.. |python| image:: https://img.shields.io/badge/python-3.8+-blue.svg
aldryn-addon? that looks like a typo

2024-03-25 10:31 UTC, fscherf commented on setup.cfg
> +[flake8]
Why are you using flake8 instead of `https://github.com/divio/lint` here?

2026-01-21 13:29 UTC, felixxm commented
Closing in favor of #77.

2026-01-21 13:29 UTC, closed without merging